name: Pull Request
on:
  pull_request:
    branches: [ master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # 4.1.6
      - name: Yarn install
        uses: hexancore/yarn-ci-install@ba9baf131eba84b6c86efb46375a530a3098bb04 # 0.1.0
      - name: Lint
        run: yarn lint
      - name: test
        uses: ./.github/actions/test
      - name: build
        run: yarn build